### ISSUE TITLE
Elements in Navbar are not positioned properly in Mobile View

### ISSUE THREAD

**Issue by HimanshuGupta-p1** [HimanshuGupta-p1/UnstopChallenge#1]
# My Assessments and Unstop Assessments are not positioned properly in Mobile View.

![image](https://github.com/HimanshuGupta-p1/UnstopChallenge/assets/87177106/888bb07c-cad2-4fc8-8151-a96164142a16)

**Comment by JaredCaprio** [comment]
What do you mean exactly?  The blue bottom border isn't aligned with the text?  The bottom border is too far away from the text?  The two NavBar items are not vertically positioned in the center or the screen?

**Comment by HimanshuGupta-p1** [comment]
> What do you mean exactly? The blue bottom border isn't aligned with the text? The bottom border is too far away from the text? The two NavBar items are not vertically positioned in the center or the screen?

exactly that is the issue!

**Comment by HimanshuGupta-p1** [comment]
All issues resolved.
